from typing import Protocol, List, Any
from queue import Queue
from media_processing_lib.data.schemas import Clip


class IMediaProcessor(Protocol):
    def __init__(self, **kwargs): ...
    def configure(self): ...
    def start(self, clips_queue: Queue) -> None: ...
    def cleanup(self) -> None: ...
    def init_frame_repo(self) -> None: ...
