from typing import Protocol, Any, List


class BasePoseEstimator(Protocol):
    def preprocess(self, data: Any) -> Any: ...
    def predict(self, data: Any) -> Any: ...
    def postprocess(self, output: Any, **kwargs) -> List: ...
